from .authentication.authentication import ROUTER as AUTHENTICATION
from .credential.credential import ROUTER as CREDENTIAL
from .version.version import ROUTER as VERSION
from .scanner.scanner import ROUTER as SCANNER
from .report.report import ROUTER as REPORT
from .target.target import ROUTER as TARGET
from .feed.feed import ROUTER as FEED
from .port.port import ROUTER as PORT
from .scan.scan import ROUTER as SCAN
from .user.user import ROUTER as USER
from .ping.ping import ROUTER as PING
from .task.task import ROUTER as TASK